export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_ALL_CUSTOMERS = 'GET_ALL_CUSTOMERS';

export const GET_SINGLE_CUSTOMER = 'GET_SINGLE_CUSTOMER';
export const RESET_CUSTOMER_LOADING = 'RESET_CUSTOMER_LOADING';
export const GET_CUSTOMER_SERVICE_NOTES = 'GET_CUSTOMER_SERVICE_NOTES';
export const GET_CUSTOMER_RECENT_ACTIVITY = 'GET_CUSTOMER_RECENT_ACTIVITY';
export const GET_CUSTOMER_CHECKLIST = 'GET_CUSTOMER_CHECKLIST';
export const CLEAR_CUSTOMERS = 'CLEAR_CUSTOMERS';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_SINGLE_EMPLOYEE = 'GET_SINGLE_EMPLOYEE';

export const GET_ROUTE_LEGS = 'GET_ROUTE_LEGS';
export const GET_ROUTE = 'GET_ROUTE';
export const ROUTE_OPTIMIZED = 'ROUTE_OPTIMIZED';

export const GET_BUSINESS_INFO = 'GET_BUSINESS_INFO';
